### ISSUE TITLE
any issues with handling block starting with /* vs /** ?

### ISSUE THREAD

**Issue by davidhabib** [SalesforceFoundation/ApexDoc#20]
ApexDoc was requiring slash star star, but that meant it mistakenly parsed keywords (class, public, global, etc.) in a normal comment.  I changed the parser to handle just slash star, and that resolved the incorrect parsing.  Any problems with this?

**Comment by ceiroa** [comment]
By normal comment you mean comments starting with double slash? Why would these be parsed?

**Comment by davidhabib** [comment]
no, i mean do I need to require the double star, vs single star.

**Comment by davidhabib** [comment]
haven't run into problems, and helps support looser formatting requirements.  So i will keep this enhancement.
