### ISSUE TITLE
Will not install and run - Eclipse Mars 4.5.1.

### ISSUE THREAD

**Issue by AgingHippie** [SalesforceFoundation/ApexDoc#48]
Doesn't work when dropped into plugins or dropins directory, doesn't work when Eclipse run as admin, doesn't work when source downloaded and plug-in development installed.  No context menu under any conditions.

**Comment by davidhabib** [comment]
support for being an Eclipse plug in has been deprecated.  you need to run it from the command line.

**Comment by AgingHippie** [comment]
It really needs some sort of UI, the paths and options are far too long and complex for a command line tool.

**Comment by kbromer** [comment]
Pull requests are welcome!
