### ISSUE TITLE
Home content and banner pages

### ISSUE THREAD

**Issue by AgingHippie** [SalesforceFoundation/ApexDoc#49]
Is there an example of working home content and banner pages?  It seems to ignore them, whether the content is bounded by &lt;html&gt;&lt;/html&gt; or not.

**Comment by kbromer** [comment]
http://developer.salesforcefoundation.org/Cumulus/ApexDocumentation/

**Comment by AgingHippie** [comment]
Yes, this is exactly what I want.  But what does my banner html file have to include in order to do this?  I tried it with and without the html tag, and it just ignores the file.  No error message, no change to the output index.html.

**Comment by davidhabib** [comment]
check out https://github.com/SalesforceFoundation/Cumulus/blob/dev/ApexDocContent/homepage.htm
and https://github.com/SalesforceFoundation/Cumulus/blob/dev/ApexDocContent/projectheader.htm

**Comment by kbromer** [comment]
Here's the doc page source: 
https://github.com/SalesforceFoundation/Cumulus/tree/gh-pages

**Comment by AgingHippie** [comment]
Got it - body tag also needed.  Thanks.

**Comment by MayTheSForceBeWithYou** [comment]
@AgingHippie 5.5 years later, this is everything to me tonight! That was quite a bit of dead link chasing before I got all the way down here. 🙏 Also, if anyone's having trouble with relative references for images/styles/etc., make sure to use the relative path of where your HTML will be generated, *NOT* where the template file(s) live.
